version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=exchange
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "exchange" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend


  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://database:5432/exchange
      - --username=admin
      - --password=admin
      - update
    volumes:
      - ./migrations:/liquibase/changelog

volumes:
  postgres-data:

networks:
  backend: