version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=exchange
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "exchange" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend


  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://database:5432/exchange
      - --username=admin
      - --password=admin
      - update
    volumes:
      - ./migrations:/liquibase/changelog

  eureka:
    build: ./eureka-server
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - database
      - liquibase-migrations

  configs:
    build: ./config-server
    ports:
      - "8888:8888"
    networks:
      - backend
    depends_on:
      - database
      - liquibase-migrations
      - eureka
    environment:
      EUREKA_URL: http://eureka:8081/eureka

  auth:
    build: ./auth
    ports:
      - "8088:8088"
    networks:
      - backend
    depends_on:
      - database
      - liquibase-migrations
      - configs
    environment:
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_URL: jdbc:postgresql://database:5432/exchange
      EUREKA_URL: http://eureka:8081/eureka
      CONFIG_URL: http://configs:8888/

  banking:
    build: ./banking
    ports:
      - "8084:8084"
    networks:
      - backend
    depends_on:
      - database
      - liquibase-migrations
      - configs
    environment:
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_URL: r2dbc:postgresql://database:5432/exchange
      EUREKA_URL: http://eureka:8081/eureka
      CONFIG_URL: http://configs:8888/

  human-resource:
    build: ./human-resource
    ports:
      - "8083:8083"
    networks:
      - backend
    depends_on:
      - database
      - liquibase-migrations
      - configs
    environment:
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_URL: jdbc:postgresql://database:5432/exchange
      EUREKA_URL: http://eureka:8081/eureka
      CONFIG_URL: http://configs:8888/
      STOCK_URL: http://stock:8089/

  stock:
    build: ./stock
    ports:
      - "8089:8089"
    networks:
      - backend
    depends_on:
      - database
      - liquibase-migrations
      - configs
    environment:
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_URL: jdbc:postgresql://database:5432/exchange
      EUREKA_URL: http://eureka:8081/eureka
      CONFIG_URL: http://configs:8888/
      STOCK_URL: http://stock:8089/
      BANKING_URL: http://banking:8084/



volumes:
  postgres-data:

networks:
  backend: