version: "3.9"

services:
  postgresql:
    image: postgres:16
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=exchange
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql


volumes:
  postgres-data: