version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=exchange
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


#  obmennik:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    ports:
#      - "8081:8080"
#    links:
#      - database
#    depends_on:
#      - database

volumes:
  postgres-data: